name: Deploy Theme to Production Environments

on:
  workflow_call:
    inputs:
      theme_name:
        description: 'Theme name (e.g., umctheme3-asia-campus)'
        required: true
        type: string
      tag_name:
        description: 'Tag to deploy (e.g., v1.0.0, latest)'
        required: true
        type: string
      # AWS Environment selection - Production environments only
      deploy_aux:
        description: 'Deploy to AUX production'
        type: boolean
        default: false
      deploy_bryce:
        description: 'Deploy to BRYCE production'
        type: boolean
        default: false
      deploy_cap_reef:
        description: 'Deploy to CAP REEF production'
        type: boolean
        default: false
      deploy_zion:
        description: 'Deploy to ZION production'
        type: boolean
        default: false
      # WP Engine settings
      wp_engine_site:
        description: 'WP Engine site name (leave empty to skip WP Engine deployment)'
        type: string
        default: ''
      # Safety settings
      dry_run:
        description: 'Run deployment in dry run mode (no actual deployment)'
        type: boolean
        default: false
      include_delete_flag:
        description: 'Include --delete flag in deployments (removes files not in source)'
        type: boolean
        default: false
    secrets:
      # AUX Production secrets
      AUX_PROD_SSH_KEY:
        required: true
      AUX_PROD_SSH_PORT:
        required: true
      AUX_PROD_SSH_USER:
        required: true
      AUX_PROD_SSH_HOST:
        required: true
      # BRYCE Production secrets
      BRYCE_PROD_SSH_KEY:
        required: true
      BRYCE_PROD_SSH_PORT:
        required: true
      BRYCE_PROD_SSH_USER:
        required: true
      BRYCE_PROD_SSH_HOST:
        required: true
      # CAP REEF Production secrets
      CAP_REEF_PROD_SSH_KEY:
        required: true
      CAP_REEF_PROD_SSH_PORT:
        required: true
      CAP_REEF_PROD_SSH_USER:
        required: true
      CAP_REEF_PROD_SSH_HOST:
        required: true
      # ZION Production secrets
      ZION_PROD_SSH_KEY:
        required: true
      ZION_PROD_SSH_PORT:
        required: true
      ZION_PROD_SSH_USER:
        required: true
      ZION_PROD_SSH_HOST:
        required: true
      # WP Engine secret
      WPE_ORG_SSHG_KEY_PRIVATE:
        required: true

jobs:
  # AUX Production
  deploy-aux-production:
    if: inputs.deploy_aux
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: aux-production
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.AUX_PROD_SSH_KEY }}
      SSH_PORT: ${{ secrets.AUX_PROD_SSH_PORT }}
      SSH_USER: ${{ secrets.AUX_PROD_SSH_USER }}
      SSH_HOST: ${{ secrets.AUX_PROD_SSH_HOST }}

  # BRYCE Production
  deploy-bryce-production:
    if: inputs.deploy_bryce
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: bryce-production
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.BRYCE_PROD_SSH_KEY }}
      SSH_PORT: ${{ secrets.BRYCE_PROD_SSH_PORT }}
      SSH_USER: ${{ secrets.BRYCE_PROD_SSH_USER }}
      SSH_HOST: ${{ secrets.BRYCE_PROD_SSH_HOST }}

  # CAP REEF Production
  deploy-cap-reef-production:
    if: inputs.deploy_cap_reef
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: capitol-reef-production
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.CAP_REEF_PROD_SSH_KEY }}
      SSH_PORT: ${{ secrets.CAP_REEF_PROD_SSH_PORT }}
      SSH_USER: ${{ secrets.CAP_REEF_PROD_SSH_USER }}
      SSH_HOST: ${{ secrets.CAP_REEF_PROD_SSH_HOST }}

  # ZION Production
  deploy-zion-production:
    if: inputs.deploy_zion
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: zion-production
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.ZION_PROD_SSH_KEY }}
      SSH_PORT: ${{ secrets.ZION_PROD_SSH_PORT }}
      SSH_USER: ${{ secrets.ZION_PROD_SSH_USER }}
      SSH_HOST: ${{ secrets.ZION_PROD_SSH_HOST }}

  # WP Engine Production
  deploy-wp-engine-production:
    if: inputs.wp_engine_site != '' && inputs.wp_engine_site != null
    uses: ./.github/workflows/theme-deploy-wpengine.yml
    with:
      theme_name: ${{ inputs.theme_name }}
      environment_type: production
      wp_engine_site: ${{ inputs.wp_engine_site }}
      tag_name: ${{ inputs.tag_name }}
      dry_run: ${{ inputs.dry_run }}
      delete: ${{ inputs.include_delete_flag }}
      cache_clear: false
    secrets:
      WPE_ORG_SSHG_KEY_PRIVATE: ${{ secrets.WPE_ORG_SSHG_KEY_PRIVATE }}
