name: Deploy Theme to Staging Environments

on:
  workflow_call:
    inputs:
      theme_name:
        description: 'Theme name (e.g., umctheme3-asia-campus)'
        required: true
        type: string
      tag_name:
        description: 'Tag to deploy (e.g., v1.0.0, latest)'
        required: true
        type: string
      # AWS Environment selection - Staging environments only
      deploy_aux:
        description: 'Deploy to AUX staging'
        type: boolean
        default: false
      deploy_bryce:
        description: 'Deploy to BRYCE staging'
        type: boolean
        default: false
      deploy_cap_reef:
        description: 'Deploy to CAP REEF staging'
        type: boolean
        default: false
      deploy_zion:
        description: 'Deploy to ZION staging'
        type: boolean
        default: false
      # WP Engine settings
      wp_engine_site:
        description: 'WP Engine site name (leave empty to skip WP Engine deployment)'
        type: string
        default: ''
      # Safety settings
      dry_run:
        description: 'Run deployment in dry run mode (no actual deployment)'
        type: boolean
        default: false
      include_delete_flag:
        description: 'Include --delete flag in deployments (removes files not in source)'
        type: boolean
        default: false
    secrets:
      # AUX Staging secrets
      AUX_STG_SSH_PRIVATE_KEY:
        required: true
      AUX_STG_SSH_PORT:
        required: true
      AUX_STG_SSH_USER:
        required: true
      AUX_STG_SSH_HOST:
        required: true
      # BRYCE Staging secrets
      BRYCE_STG_SSH_PRIVATE_KEY:
        required: true
      BRYCE_STG_SSH_PORT:
        required: true
      BRYCE_STG_SSH_USER:
        required: true
      BRYCE_STG_SSH_HOST:
        required: true
      # CAP REEF Staging secrets
      CAP_REEF_STG_SSH_PRIVATE_KEY:
        required: true
      CAP_REEF_STG_SSH_PORT:
        required: true
      CAP_REEF_STG_SSH_USER:
        required: true
      CAP_REEF_STG_SSH_HOST:
        required: true
      # ZION Staging secrets
      ZION_STG_SSH_PRIVATE_KEY:
        required: true
      ZION_STG_SSH_PORT:
        required: true
      ZION_STG_SSH_USER:
        required: true
      ZION_STG_SSH_HOST:
        required: true
      # WP Engine secret
      WPE_ORG_SSHG_KEY_PRIVATE:
        required: true

jobs:
  # AUX Staging
  deploy-aux-staging:
    if: inputs.deploy_aux
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: aux-staging
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.AUX_STG_SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.AUX_STG_SSH_PORT }}
      SSH_USER: ${{ secrets.AUX_STG_SSH_USER }}
      SSH_HOST: ${{ secrets.AUX_STG_SSH_HOST }}

  # BRYCE Staging
  deploy-bryce-staging:
    if: inputs.deploy_bryce
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: bryce-staging
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.BRYCE_STG_SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.BRYCE_STG_SSH_PORT }}
      SSH_USER: ${{ secrets.BRYCE_STG_SSH_USER }}
      SSH_HOST: ${{ secrets.BRYCE_STG_SSH_HOST }}

  # CAP REEF Staging
  deploy-cap-reef-staging:
    if: inputs.deploy_cap_reef
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: capitol-reef-staging
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.CAP_REEF_STG_SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.CAP_REEF_STG_SSH_PORT }}
      SSH_USER: ${{ secrets.CAP_REEF_STG_SSH_USER }}
      SSH_HOST: ${{ secrets.CAP_REEF_STG_SSH_HOST }}

  # ZION Staging
  deploy-zion-staging:
    if: inputs.deploy_zion
    uses: ./.github/workflows/theme-deploy-aws.yml
    with:
      environment: zion-staging
      theme_name: ${{ inputs.theme_name }}
      tag_name: ${{ inputs.tag_name }}
      delete: ${{ inputs.include_delete_flag }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.ZION_STG_SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.ZION_STG_SSH_PORT }}
      SSH_USER: ${{ secrets.ZION_STG_SSH_USER }}
      SSH_HOST: ${{ secrets.ZION_STG_SSH_HOST }}

  # WP Engine Staging
  deploy-wp-engine-staging:
    if: inputs.wp_engine_site != '' && inputs.wp_engine_site != null
    uses: ./.github/workflows/theme-deploy-wpengine.yml
    with:
      theme_name: ${{ inputs.theme_name }}
      environment_type: staging
      wp_engine_site: ${{ inputs.wp_engine_site }}
      tag_name: ${{ inputs.tag_name }}
      dry_run: ${{ inputs.dry_run }}
      delete: ${{ inputs.include_delete_flag }}
      cache_clear: false
    secrets:
      WPE_ORG_SSHG_KEY_PRIVATE: ${{ secrets.WPE_ORG_SSHG_KEY_PRIVATE }}